# Generated by Django 4.2.1 on 2023-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='app_version',
            field=models.CharField(default='', max_length=10),
        ),
    ]
